<a href="https://colab.research.google.com/github/hyeon9698/Donghyeon_Cho/blob/main/week_4/week_4_Logistic_Regression_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 다중선형회귀(Multiple Linear Regression)
- 수치형 설명변수(x)와 연속형 숫자로 이뤄진 종속변수(y) 간의 관계를 선형으로 가정하고 이를 가장 잘 표현할 수 있는 회귀계수(B)를 데이터로부터 추정하는 것

### 정규화
- variance를 감소시켜 일반화 성능을 높이는 기법
- bias, variance 둘다 낮으면 좋음
- 정규화 정도 C = 1/lambda

### Bias-Variance Decomposition
- 일반화(generalization) 성능을 높이는 정규화(Regularization), 앙상블(ensemble) 기법의 이론적 배경
- 학습에 쓰지 않은 미래 데이터에 대한 오차의 기대값을 모델의 Bias와 ariance로 분해하자는 내용

### 로지스틱 함수(Logistic function)
- x값으로 어떤 값이든 받을 수가 있지만 출력 결과(y)는 항상 0에서 1사이 값이 됨
- 시그모이드 함수라고 명명하기도 함

In [1]:
# 데이터 불러오기
import seaborn as sns # seaborn을 불러오고 SNS로 축약
iris = sns.load_dataset('iris')  # iris라는 변수명으로 Iris data를 download
X = iris.drop('species', axis=1)
y = iris['species']
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [2]:
from sklearn.preprocessing import LabelEncoder
classle = LabelEncoder()
y = classle.fit_transform(iris['species'].values)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

In [4]:
# 표준화
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [5]:
from sklearn.linear_model import LogisticRegression
Logit = LogisticRegression(C=200, random_state=11)
l_1=Logit.fit(X_train_std, y_train)
y_train_pred = Logit.predict(X_train_std)
y_test_pred = Logit.predict(X_test_std)

In [6]:
# Accuracy score
from sklearn.metrics import accuracy_score
print(accuracy_score(y_train, y_train_pred))
print(accuracy_score(y_test, y_test_pred))

0.9809523809523809
1.0


In [8]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_test_pred))

[[15  0  0]
 [ 0 15  0]
 [ 0  0 15]]


# 로지스틱 회귀 실험
- 데이터셋: 와인 데이터
- 학습/시험 데이터: x_train/x_test(13개의 특성변수)
- 학습/시험 데이터 라벨: y_train/y_test -> (1,2,3)로 이미 범주형으로 지정되어 있음
- 다양한 규제강도에 따른 실험
    - L1, L2 규제화
    - C=1/lambda로 규제화
    - 테스트 데이터의 라벨을 알 수 없을 경우, 학습데이터의 일부를 검증데이터(validation data)로 구성하여 데스트
- 다양한 규제강도에 따른 초정계수 실험
    - 규제강도가 클수록 추정된 계수들의 절대값이 작아짐
    - L1 규제화의 경우 규제강도가 클수록 계수에 0이 많아짐. 즉, 계수에 대응하는 특성변수를 제거하는 역할을 담당함.


In [9]:
import pandas as pd
import numpy as np

In [11]:
# 데이터 불러오기. y값은 이미 범주형으로 되어있음.
dat_wine=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/'
                     'wine/wine.data',header=None)
dat_wine.columns = ['class label', 'alchohol', 'malic acid', 'ash', 
                    'alcalinity of ash', 'magnesium', 'total phenols', 
                    'flavanoids', 'nonflavanoid phenols', 
                    'proanthocyanins', 'color intensity', 'hue', 
                    'OD208', 'proline']  # Column names
print('class label:', np.unique(dat_wine['class label']))  # Class 출력
dat_wine.head()

class label: [1 2 3]


class label  alchohol  malic acid  ...   hue  OD208  proline
0            1     14.23        1.71  ...  1.04   3.92     1065
1            1     13.20        1.78  ...  1.05   3.40     1050
2            1     13.16        2.36  ...  1.03   3.17     1185
3            1     14.37        1.95  ...  0.86   3.45     1480
4            1     13.24        2.59  ...  1.04   2.93      735

[5 rows x 14 columns]

In [19]:
# 전체 data를 training set과 test set으로 split
from sklearn.model_selection import train_test_split
X, y = dat_wine.iloc[:,1:].values, dat_wine.iloc[:,0].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

In [22]:
# 표준화
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
X_train_std = std.fit_transform(X_train)
X_test_std = std.transform(X_test)

In [23]:
# Logistic Regression with L2 or L1 Regularization
from sklearn.linear_model import LogisticRegression
lr2_10 = LogisticRegression(penalty='l2', C=10.0, solver='saga')  # L2 with C(=1/λ)=10
lr2_1 = LogisticRegression(penalty='l2', C=1.0, solver='saga')    # L2 with C(=1/λ)=1
lr2_0_1 = LogisticRegression(penalty='l2', C=0.1, solver='saga')  # L2 with C(=1/λ)=0.1

lr1_10 = LogisticRegression(penalty='l1', C=10.0, solver='saga')  # L1 with C(=1/λ)=10
lr1_1 = LogisticRegression(penalty='l1', C=1.0, solver='saga')    # L1 with C(=1/λ)=1
lr1_0_1 = LogisticRegression(penalty='l1', C=0.1, solver='saga')  # L1 with C(=1/λ)=0.1

In [24]:
# 규제화 방법(L2 or L1)과 규제강도(λ)를 바꿔가며 accuracy score 계산
lr2_10.fit(X_train_std, y_train)
print('Training accuracy with L2 and λ=0.1:', lr2_10.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=0.1:', lr2_10.score(X_test_std, y_test))

lr2_1.fit(X_train_std, y_train)  # warning..
print('Training accuracy with L2 and λ=1:', lr2_1.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=1:', lr2_1.score(X_test_std, y_test))

lr2_0_1.fit(X_train_std, y_train)
print('Training accuracy with L2 and λ=10:', lr2_0_1.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=10:', lr2_0_1.score(X_test_std, y_test))

lr1_10.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=0.1:', lr1_10.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=0.1:', lr1_10.score(X_test_std, y_test))

lr1_1.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=1:', lr1_1.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=1:', lr1_1.score(X_test_std, y_test))

lr1_0_1.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=10:', lr1_0_1.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=10:', lr1_0_1.score(X_test_std, y_test))

Training accuracy with L2 and λ=0.1: 1.0
Test accuracy with L2 and λ=0.1: 0.9814814814814815
Training accuracy with L2 and λ=1: 1.0
Test accuracy with L2 and λ=1: 0.9814814814814815
Training accuracy with L2 and λ=10: 1.0
Test accuracy with L2 and λ=10: 1.0
Training accuracy with L1 and λ=0.1: 1.0
Test accuracy with L1 and λ=0.1: 0.9814814814814815
Training accuracy with L1 and λ=1: 1.0
Test accuracy with L1 and λ=1: 1.0
Training accuracy with L1 and λ=10: 0.967741935483871
Test accuracy with L1 and λ=10: 0.9444444444444444


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


In [25]:
# L2 규제의 규제강도(C=1/λ)를 바꿔가며 계수 추정치 관찰
print(lr2_10.intercept_)
print(lr2_1.intercept_)
print(lr2_0_1.intercept_)

print(lr2_10.coef_)
print(lr2_1.coef_)
print(lr2_0_1.coef_)

[ 0.33681126  0.60300002 -0.93981127]
[ 0.28431433  0.60472514 -0.88903947]
[ 0.06853617  0.45692561 -0.52546178]
[[ 1.20574796  0.16828097  0.39230678 -1.51705874  0.08935668  0.40728865
   0.84684321 -0.29153423  0.04238326  0.17269416  0.07455204  0.96724624
   1.40717047]
 [-1.54567318 -0.44231894 -1.265256    1.2302992  -0.32055204 -0.54155557
   0.85300708  0.40882064  0.41267369 -1.34200284  1.14533732  0.05143326
  -1.76621881]
 [ 0.33992522  0.27403798  0.87294922  0.28675954  0.23119535  0.13426692
  -1.69985028 -0.11728641 -0.45505694  1.16930869 -1.21988935 -1.0186795
   0.35904834]]
[[ 0.75465963  0.06147631  0.233128   -0.8924215   0.02634462  0.29446681
   0.56062818 -0.20740136  0.13469387  0.12776906  0.10230581  0.61816212
   0.90925521]
 [-0.98665478 -0.32315609 -0.6518379   0.66757644 -0.22940426 -0.20684259
   0.43799551  0.19810766  0.24454236 -0.77969054  0.63752626  0.08603635
  -1.03446864]
 [ 0.23199516  0.26167979  0.4187099   0.22484507  0.20305965 -0.087624

In [26]:
# L1 규제의 규제강도(C=1/λ)를 바꿔가며 계수 추정치 관찰
print(lr1_10.intercept_)
print(lr1_1.intercept_)
print(lr1_0_1.intercept_)

print(lr1_10.coef_)
print(lr1_1.coef_)
print(lr1_0_1.coef_)

[ 0.32338113  0.59746247 -0.9208436 ]
[ 0.29112533  0.53925988 -0.8303852 ]
[ 0.05085392  0.30693666 -0.35779057]
[[ 1.20082912  0.          0.20258386 -1.65573308  0.          0.23047386
   0.74829279 -0.11400351  0.          0.          0.          0.95108667
   1.40707851]
 [-1.81850289 -0.4249125  -1.48858674  1.07482054 -0.36863186 -0.39958049
   0.66229502  0.46683768  0.23053365 -1.51632518  1.12529153  0.
  -1.96952354]
 [ 0.09051697  0.12640126  0.77118272  0.05401098  0.0854582   0.
  -1.93808492  0.         -0.38862449  1.21846095 -1.23826676 -0.98337274
   0.03690476]]
[[ 0.01282313  0.          0.         -1.17414285  0.          0.
   0.0224406   0.          0.          0.          0.          0.62433047
   0.99532758]
 [-1.58243    -0.14561634 -0.77008669  0.04358902 -0.06981152  0.
   0.          0.14104554  0.         -1.0449058   0.22148177  0.
  -1.19096365]
 [ 0.          0.          0.          0.          0.          0.
  -2.11107072  0.         -0.01691192  0.230